name: Docker Build

on:
  pull_request:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 0,1'

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: anggit86
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./
          file: ./Dockerfile
          run: echo ${{ secrets.RCLONE }} > ~/.config/rclone/rclone.conf
          push: true
          tags: anggit86/dev:latest


      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
